version: '3.3'
services:
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: 'jwt_db'
      MYSQL_USER: 'jwt_user'
      MYSQL_PASSWORD: 'jwt_password'
      MYSQL_ROOT_PASSWORD: 'jwt_password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - jwt-db:/var/lib/mysql
volumes:
  jwt-db: