spring:
  profiles:
    active: ShortLived
  datasource:
    url: jdbc:mysql://localhost:3306/jwt_db
    driver-class-name: com.mysql.jdbc.Driver
    username: jwt_user
    password: jwt_password
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect


jwt:
  short-lived:
    ttl: 30
    secret: ZWQ1ODRmNzUtNzQ2MS00NWM2LWI3OGYtZDM2NDA4ZWUwNDcw