spring:
  profiles:
    active: Novel, CalculateCosts
  datasource:
    url: jdbc:mysql://localhost:3306/jwt_db
    driver-class-name: com.mysql.jdbc.Driver
    username: jwt_user
    password: jwt_password
    hikari:
      maximum-pool-size: 100
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect


jwt:
  black-list:
    secret: ZWQ1ODRmNzUtNzQ2MS00NWM2LWI3OGYtZDM2NDA4ZWUwNDcw
  short-lived:
    secret: ZWQ1ODRmNzUtNzQ2MS00NWM2LWI3OGYtZDM2NDA4ZWUwNDcw